# Generated by Django 4.1.5 on 2023-02-04 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=10, null=True)),
                ('recommended_movie_list', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField()),
                ('LoginUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batchtrain', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
