# Generated by Django 4.1.5 on 2023-02-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_model_batchtrain_model_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchtrain',
            name='model_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='batchtrain',
            name='model_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
