# Generated by Django 4.1.5 on 2023-01-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_rec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpuser',
            name='MBTI',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tmpuser',
            name='ennear_ans',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tmpuser',
            name='ennear_res',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tmpuser',
            name='prefer_movie_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tmpuser',
            name='recommended_character_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
