# Generated by Django 4.1.5 on 2023-01-26 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_rec', '0003_alter_tmpuser_prefer_movie_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpuser',
            name='LoginUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
