# Generated by Django 4.1.5 on 2023-01-26 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_rec', '0004_tmpuser_loginuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpuser',
            name='LoginUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tmpuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
