# Generated by Django 4.1.5 on 2023-01-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_rec', '0005_alter_tmpuser_loginuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmpuser',
            old_name='ennear_ans',
            new_name='ennea_ans1',
        ),
        migrations.RenameField(
            model_name='tmpuser',
            old_name='ennear_res',
            new_name='ennea_res',
        ),
        migrations.AddField(
            model_name='tmpuser',
            name='ennea_ans2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
