# Generated by Django 4.1.5 on 2023-01-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_rec', '0006_rename_ennear_ans_tmpuser_ennea_ans1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmpuser',
            old_name='ennea_ans1',
            new_name='ennear_ans',
        ),
        migrations.RenameField(
            model_name='tmpuser',
            old_name='ennea_ans2',
            new_name='ennear_res',
        ),
        migrations.RemoveField(
            model_name='tmpuser',
            name='ennea_res',
        ),
    ]
