# Generated by Django 4.1.5 on 2023-01-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_rec', '0008_rename_ennear_ans_tmpuser_ennea_ans1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpuser',
            name='prefer_movie_id',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='tmpuser',
            name='recommended_character_id',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
