# Generated by Django 4.1.5 on 2023-02-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_rec', '0009_alter_tmpuser_prefer_movie_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpuser',
            name='charming_character_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tmpuser',
            name='charming_character_similarity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tmpuser',
            name='recommended_character_similarity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tmpuser',
            name='prefer_movie_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tmpuser',
            name='recommended_character_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
