# Generated by Django 4.1.5 on 2023-02-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_rec', '0010_tmpuser_charming_character_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmpuser',
            old_name='charming_character_similarity',
            new_name='charming_character_sim',
        ),
        migrations.RenameField(
            model_name='tmpuser',
            old_name='recommended_character_similarity',
            new_name='recommended_character_sim',
        ),
    ]
