# Generated by Django 4.1.5 on 2023-02-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_rec', '0011_rename_charming_character_similarity_tmpuser_charming_character_sim_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmpuser',
            old_name='charming_character_id',
            new_name='fit_character_id',
        ),
        migrations.RenameField(
            model_name='tmpuser',
            old_name='charming_character_sim',
            new_name='fit_character_sim',
        ),
    ]
