# Generated by Django 4.1.5 on 2023-02-07 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_rec', '0012_rename_charming_character_id_tmpuser_fit_character_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('LoginUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characterlike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
