# Generated by Django 4.1.5 on 2023-02-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_rec', '0013_characterlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpuser',
            name='feedback',
            field=models.IntegerField(default=0),
        ),
    ]
