# Generated by Django 4.1.5 on 2023-02-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_rec', '0014_tmpuser_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpuser',
            name='annoy_recommend_movies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tmpuser',
            name='bts_recommend_movies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
