# Generated by Django 4.1.5 on 2023-02-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_rec', '0015_tmpuser_annoy_recommend_movies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpuser',
            name='annoy_bts_ratio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
